### ISSUE TITLE
   Report an error about“ wandb.init(project="sdm") ”  

### ISSUE THREAD

**Issue by WenBingo** [ispamm/GESCO#6]
report an error about“ wandb.init(project="sdm") ”  

Traceback (most recent call last):
  File "D:\Anaconda\envs\pytorch\lib\site-packages\wandb\sdk\wandb_init.py", line 1173, in init
    raise e
  File "D:\Anaconda\envs\pytorch\lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    wi.setup(kwargs)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\wandb\sdk\wandb_init.py", line 289, in setup
    wandb_login._login(
  File "D:\Anaconda\envs\pytorch\lib\site-packages\wandb\sdk\wandb_login.py", line 298, in _login
    wlogin.prompt_api_key()
  File "D:\Anaconda\envs\pytorch\lib\site-packages\wandb\sdk\wandb_login.py", line 228, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])

**Comment by MeowDWing** [comment]
you should log in wandb before you run the program.
you need open www.wandb.com and sign up an account, and then you can see the quickstart (https://wandb.ai/quickstart) to know how to use it.

**Comment by WenBingo** [comment]
thanks for your answer ， i will try this way
