### ISSUE TITLE
ModuleNotFoundError for unet_edited in guided_diffusion/script_util.py

### ISSUE THREAD

**Issue by wwqqq16** [ispamm/GESCO#9]
Description:
Environment:
Python version: (your Python version)
Operating System: macOS
Steps to Reproduce:
Clone the GESCO-main repository.
Navigate to the repository directory.
Run the command python image_train.py --data_dir ./data --dataset_mode cityscapes... (other flags)
Expected Behavior:
The script should run without any issues.

Actual Behavior:
Received a ModuleNotFoundError for guided_diffusion.unet_edited.

Traceback (most recent call last):
  File "/Users/wweng/Desktop/GESCO-main/image_train.py", line 11, in <module>
    from guided_diffusion.script_util import (
  File "/Users/wweng/Desktop/GESCO-main/guided_diffusion/script_util.py", line 7, in <module>
    from .unet_edited import UNetModelSPADE, UNetModelEncOnly
ModuleNotFoundError: No module named 'guided_diffusion.unet_edited'

Additional Information:
Upon inspecting the guided_diffusion directory, the following modules were found:

__init__.py
fp16_util.py
gaussian_diffusion.py
image_datasets.py
losses.py
nn.py
resample.py
respace.py
script_util.py
train_util.py
unet.py
The module unet_edited is not present, causing the ModuleNotFoundError.

**Comment by dmwlx** [comment]
同样的错误，怎么解决

**Comment by wwqqq16** [comment]
> 同样的错误，怎么解决

I deleted all the module unet_edited.py related lines in guided_diffusion directory and just use module unet.py for training process, and it works

**Comment by dmwlx** [comment]
可以分享一下你的源码吗，谢谢你。我的邮箱是:2607711574@qq.com

**Comment by TWTWTWTWTWTWTWTW** [comment]
直接把和unet_edited相关的注释掉就好了，用不上的

**Comment by wwqqq16** [comment]
> 直接把和unet_edited相关的注释掉就好了，用不上的

确实，没用sampling的result也一样

**Comment by dmwlx** [comment]
注释了后面又出现这个错误：
if in_channels % groups != 0:
TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'

**Comment by laopidu** [comment]
> 注释了后面又出现这个错误： if in_channels % groups != 0: TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'

解决了吗？我也出现了这个问题！

**Comment by 18729595064** [comment]
同学你好，呜呜呜，想问下你跑通了吗，请问可以分享下你的源码吗？感谢！！！祝同学学业顺利

**Comment by 18729595064** [comment]
同学你好，呜呜呜，想问下你跑通了吗，请问可以分享下你的源码吗？感谢！！！祝同学学业顺利！！邮箱：2757336070@qq.com
